credits:
  - name: "Timofey Yakubov"
    role: "Creator & Main Developer"
    github: "Timon4ikRU"
  
  - name: "DeepSeek AI"
    role: "Co-Translator (EN)"
    url: "https://deepseek.com"
    note: "AI-assisted English translation"
